version: '3'
services:
  graph-node:
    network_mode: host
    image: graphprotocol/graph-node
    ports:
      - '8000:8000'  # GraphQL Query endpoint
      - '8001:8001'  # GraphQL Subscription endpoint
      - '8020:8020'  # Admin endpoint
      - '8040:8040'  # Prometheus metrics endpoint
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: 192.168.1.165
      postgres_user: lux
      postgres_pass: oi1dAc9bad8MSc2da51a2544f0cb8e16lb21A
      postgres_db: graph_luxnet
      ipfs: '192.168.1.165:5555'
      ethereum: 'lux:http://luxnet:8080'
      GRAPH_LOG: debug
      RUST_BACKTRACE: 1
